name: toss_intro_page_lego
description: "toss style intro screen for flutter"
#publish_to: 'none'
repository: https://github.com/flutter-lego/toss_intro_page_lego

version: 1.0.2

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  june_flow_util:
  styled_widget: #@add
  modal_bottom_sheet: #@add
  tuple: #@add
  auto_size_text: #@add
  infinite_listview: #@add
  gap: #@add
  flutter_color: #@add

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  assets:
    - assets/lego/toss_intro_page_lego/
  uses-material-design: true

topics:
  - lego